service: take-home-assessment

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  get_all_orders:
    handler: handler.get_all_orders
    events:
      - httpApi:
          path: /orders
          method: get
  get_service_by_id:
    handler: handler.get_service_by_id
    events:
      - httpApi:
          path: /services/{id}
          method: get
  get_all_services:
    handler: handler.get_all_services
    events:
      - httpApi:
          path: /services
          method: get
