"""Added account table

Revision ID: 16fd4adcd719
Revises: 52ad861d3c4c
Create Date: 2022-08-14 11:08:09.382903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16fd4adcd719"
down_revision = "52ad861d3c4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_on",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "modified_on",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ordersItem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("service", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ordersItem")
    op.drop_table("orders")
    # ### end Alembic commands ###
