"""Added boolean field

Revision ID: 3de3935c3110
Revises: 16fd4adcd719
Create Date: 2022-08-14 11:13:45.944731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3de3935c3110"
down_revision = "16fd4adcd719"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("status", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
