"""gixed relantionships

Revision ID: dc60a80e8c8d
Revises: 3de3935c3110
Create Date: 2022-08-14 11:28:19.046723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dc60a80e8c8d"
down_revision = "3de3935c3110"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ordersItem_ibfk_2", "ordersItem", type_="foreignkey")
    op.drop_constraint("ordersItem_ibfk_1", "ordersItem", type_="foreignkey")
    op.drop_column("ordersItem", "order")
    op.drop_column("ordersItem", "service")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ordersItem",
        sa.Column(
            "service",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ordersItem",
        sa.Column(
            "order", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "ordersItem_ibfk_1", "ordersItem", "orders", ["order"], ["id"]
    )
    op.create_foreign_key(
        "ordersItem_ibfk_2", "ordersItem", "services", ["service"], ["id"]
    )
    # ### end Alembic commands ###
